def translate_soccer_team_name(csv_team_name):
    team_mapping = {
        "Arsenal": "Arsenal",
        "Aston Villa": "Aston Villa",
        "Birmingham": "Birmingham City",
        "Blackburn": "Blackburn",
        "Blackpool": "Blackpool",
        "Bolton": "Bolton",
        "Bournemouth": "Bournemouth",
        "Brentford": "Brentford",
        "Brighton": "Brighton and Hove Albion",
        "Burnley": "Burnley",
        "Cardiff": "Cardiff City",
        "Chelsea": "Chelsea",
        "Crystal Palace": "Crystal Palace",
        "Everton": "Everton",
        "Fulham": "Fulham",
        "Huddersfield": "Huddersfield Town",
        "Hull": "Hull City",
        "Ipswich": "Ipswich Town",
        "Leeds": "Leeds United",
        "Leicester": "Leicester City",
        "Liverpool": "Liverpool",
        "Luton": "Luton",
        "Man City": "Manchester City",
        "Man United": "Manchester United",
        "Middlesbrough": "Middlesbrough",
        "Newcastle": "Newcastle United",
        "Norwich": "Norwich City",
        "Nott'm Forest": "Nottingham Forest",
        "QPR": "Queens Park Rangers",
        "Reading": "Reading",
        "Sheffield United": "Sheffield United",
        "Southampton": "Southampton",
        "Stoke": "Stoke City",
        "Sunderland": "Sunderland",
        "Swansea": "Swansea City",
        "Tottenham": "Tottenham Hotspur",
        "Watford": "Watford",
        "West Brom": "West Bromwich Albion",
        "West Ham": "West Ham United",
        "Wigan": "Wigan Athletic",
        "Wolves": "Wolverhampton Wanderers"
    }
    return team_mapping.get(csv_team_name, csv_team_name)