"""Create teams and nba_games tables

Revision ID: d43083648ae1
Revises: 
Create Date: 2025-04-07 13:31:32.591967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43083648ae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('nba_games',
    sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_site', sa.String(length=50), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_points', sa.Integer(), nullable=False),
    sa.Column('away_points', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('total_margin', sa.Float(), nullable=False),
    sa.Column('home_line', sa.Float(), nullable=False),
    sa.Column('away_line', sa.Float(), nullable=False),
    sa.Column('quarter_scores', sa.JSON(), nullable=False),
    sa.Column('home_halftime_points', sa.Integer(), nullable=False),
    sa.Column('away_halftime_points', sa.Integer(), nullable=False),
    sa.Column('sdql_game_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('sdql_game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba_games')
    op.drop_table('teams')
    # ### end Alembic commands ###
