"""Shared team-slug utilities for the 6 sports with team-page infrastructure
(nba, nfl, mlb, nhl, ncaaf, ncaab). Mirrors getstam-react/src/utils/teamSlugUtils.ts.

Lives outside app.py so it can be imported by both app.py and API route/service
modules without creating a circular import (app.py imports blueprints from
api/routes/*, so those modules can't import back from app.py).
"""
import re

# oddsApiNames for each sport — mirrors teamSlugUtils.ts
SPORT_TEAMS = {
    'nba': [
        'Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets',
        'Chicago Bulls', 'Cleveland Cavaliers', 'Dallas Mavericks', 'Denver Nuggets',
        'Detroit Pistons', 'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers',
        'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies', 'Miami Heat',
        'Milwaukee Bucks', 'Minnesota Timberwolves', 'New Orleans Pelicans', 'New York Knicks',
        'Oklahoma City Thunder', 'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns',
        'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs', 'Toronto Raptors',
        'Utah Jazz', 'Washington Wizards',
    ],
    'nfl': [
        'Arizona Cardinals', 'Atlanta Falcons', 'Baltimore Ravens', 'Buffalo Bills',
        'Carolina Panthers', 'Chicago Bears', 'Cincinnati Bengals', 'Cleveland Browns',
        'Dallas Cowboys', 'Denver Broncos', 'Detroit Lions', 'Green Bay Packers',
        'Houston Texans', 'Indianapolis Colts', 'Jacksonville Jaguars', 'Kansas City Chiefs',
        'Las Vegas Raiders', 'Los Angeles Chargers', 'Los Angeles Rams', 'Miami Dolphins',
        'Minnesota Vikings', 'New England Patriots', 'New Orleans Saints', 'New York Giants',
        'New York Jets', 'Philadelphia Eagles', 'Pittsburgh Steelers', 'San Francisco 49ers',
        'Seattle Seahawks', 'Tampa Bay Buccaneers', 'Tennessee Titans', 'Washington Commanders',
    ],
    'mlb': [
        'Arizona Diamondbacks', 'Atlanta Braves', 'Baltimore Orioles', 'Boston Red Sox',
        'Chicago Cubs', 'Chicago White Sox', 'Cincinnati Reds', 'Cleveland Guardians',
        'Colorado Rockies', 'Detroit Tigers', 'Houston Astros', 'Kansas City Royals',
        'Los Angeles Angels', 'Los Angeles Dodgers', 'Miami Marlins', 'Milwaukee Brewers',
        'Minnesota Twins', 'New York Mets', 'New York Yankees', 'Athletics',
        'Philadelphia Phillies', 'Pittsburgh Pirates', 'San Diego Padres', 'San Francisco Giants',
        'Seattle Mariners', 'St. Louis Cardinals', 'Tampa Bay Rays', 'Texas Rangers',
        'Toronto Blue Jays', 'Washington Nationals',
    ],
    'nhl': [
        'Anaheim Ducks', 'Arizona Coyotes', 'Boston Bruins', 'Buffalo Sabres',
        'Calgary Flames', 'Carolina Hurricanes', 'Chicago Blackhawks', 'Colorado Avalanche',
        'Columbus Blue Jackets', 'Dallas Stars', 'Detroit Red Wings', 'Edmonton Oilers',
        'Florida Panthers', 'Los Angeles Kings', 'Minnesota Wild', 'Montréal Canadiens',
        'Nashville Predators', 'New Jersey Devils', 'New York Islanders', 'New York Rangers',
        'Ottawa Senators', 'Philadelphia Flyers', 'Pittsburgh Penguins', 'San Jose Sharks',
        'Seattle Kraken', 'St Louis Blues', 'Tampa Bay Lightning', 'Toronto Maple Leafs',
        'Utah Mammoth', 'Vancouver Canucks', 'Vegas Golden Knights', 'Washington Capitals',
        'Winnipeg Jets',
    ],
    # Mirrors the NCAAF team names in shared_utils.py's convert_team_name() so slug
    # resolution recognizes the same universe of teams (FBS + FCS) that live game/odds
    # matching does. Keep in sync with that map if the Odds API adds/renames schools.
    'ncaaf': [
        'Abilene Christian Wildcats', 'Air Force Falcons', 'Arkansas-Pine Bluff Golden Lions',
        'Akron Zips', 'Arkansas State Red Wolves', 'Alabama Crimson Tide',
        'Alabama A&M Bulldogs', 'Albany Great Danes', 'Alcorn State Braves',
        'Appalachian State Mountaineers', 'Arkansas Razorbacks', 'Army Black Knights',
        'Arizona Wildcats', 'Auburn Tigers', 'Arizona State Sun Devils',
        'Ball State Cardinals', 'Baylor Bears', 'Boston College Eagles',
        'Boise State Broncos', 'Bowling Green Falcons', 'Bryant Bulldogs',
        'Bucknell Bison', 'Buffalo Bulls', 'BYU Cougars',
        'California Golden Bears', 'Campbell Camels', 'Central Arkansas Bears',
        'Central Connecticut Blue Devils', 'UC Davis Aggies', 'UCF Knights',
        'Charlotte 49ers', 'Charleston Southern Buccaneers', 'Cincinnati Bearcats',
        'Clemson Tigers', 'Colgate Raiders', 'Central Michigan Chippewas',
        'Colorado Buffaloes', 'Columbia Lions', 'Connecticut Huskies',
        'Bethune-Cookman Wildcats', 'Cornell Big Red', 'Colorado State Rams',
        'Cal Poly Mustangs', 'Sacramento State Hornets', 'Coastal Carolina Chanticleers',
        'The Citadel Bulldogs', 'Dartmouth Big Green', 'Davidson Wildcats',
        'Dayton Flyers', 'Delaware Blue Hens', 'Drake Bulldogs',
        'Delaware State Hornets', 'Duke Blue Devils', 'Duquesne Dukes',
        'East Carolina Pirates', 'Eastern Illinois Panthers', 'Eastern Kentucky Colonels',
        'Elon Phoenix', 'Eastern Michigan Eagles', 'East Tennessee State Buccaneers',
        'Eastern Washington Eagles', 'Florida A&M Rattlers', 'Florida Atlantic Owls',
        'Florida International Golden Panthers', 'Florida Gators', 'Florida State Seminoles',
        'Fordham Rams', 'Fresno State Bulldogs', 'Furman Paladins',
        'Gardner-Webb Bulldogs', 'Georgia State Panthers', 'Georgia Bulldogs',
        'Grambling Tigers', 'Georgia Southern Eagles', 'Georgia Tech Yellow Jackets',
        'Georgetown Hoyas', 'Hawaii Rainbow Warriors', 'Houston Baptist Huskies',
        'Holy Cross Crusaders', 'Houston Cougars', 'Howard Bison',
        'Harvard Crimson', 'Idaho Vandals', 'Idaho State Bengals',
        'Illinois Fighting Illini', 'Illinois State Redbirds', 'Indiana Hoosiers',
        'Indiana State Sycamores', 'Iowa Hawkeyes', 'Incarnate Word Cardinals',
        'Iowa State Cyclones', 'Jackson State Tigers', 'James Madison Dukes',
        'Jacksonville State Gamecocks', 'Kansas Jayhawks', 'Kansas State Wildcats',
        'Kennesaw State Owls', 'Kent State Golden Flashes', 'Kentucky Wildcats',
        'Lafayette Leopards', 'Lamar Cardinals', 'Liberty Flames',
        'Long Island University Sharks', 'UL Monroe Warhawks', 'Louisville Cardinals',
        'LSU Tigers', 'Louisiana Tech Bulldogs', 'Maine Black Bears',
        'Marist Red Foxes', 'Maryland Terrapins', 'UMass Minutemen',
        'Michigan State Spartans', 'Memphis Tigers', 'Mercer Bears',
        'Miami Hurricanes', 'Miami (OH) RedHawks', 'Michigan Wolverines',
        'Minnesota Golden Gophers', 'Ole Miss Rebels', 'Missouri Tigers',
        'McNeese Cowboys', 'Monmouth Hawks', 'Montana State Bobcats',
        'Montana Grizzlies', 'Morgan State Bears', 'Merrimack Warriors',
        'Marshall Thundering Herd', 'Mississippi State Bulldogs', 'Middle Tennessee Blue Raiders',
        'Murray State Racers', 'Mississippi Valley State Delta Devils', 'Missouri State Bears',
        'North Alabama Lions', 'Navy Midshipmen', 'Northern Arizona Lumberjacks',
        'North Carolina Tar Heels', 'North Carolina A&T Aggies', 'North Carolina Central Eagles',
        'Northern Colorado Bears', 'NC State Wolfpack', 'North Dakota State Bison',
        'Nebraska Cornhuskers', 'Nevada Wolf Pack', 'Norfolk State Spartans',
        'New Hampshire Wildcats', 'Nicholls Colonels', 'Northern Illinois Huskies',
        'Northern Iowa Panthers', 'New Mexico State Aggies', 'New Mexico Lobos',
        'Northwestern Wildcats', 'Northwestern State Demons', 'Notre Dame Fighting Irish',
        'North Texas Mean Green', 'Ohio State Buckeyes', 'Ohio Bobcats',
        'Oklahoma Sooners', 'Oklahoma State Cowboys', 'Old Dominion Monarchs',
        'Oregon Ducks', 'Oregon State Beavers', 'Austin Peay Governors',
        'Pennsylvania Quakers', 'Pittsburgh Panthers', 'Penn State Nittany Lions',
        'Portland State Vikings', 'Presbyterian College Blue Hose', 'Princeton Tigers',
        'Prairie View Panthers', 'Purdue Boilermakers', 'Rice Owls',
        'Richmond Spiders', 'Robert Morris Colonials', 'Rutgers Scarlet Knights',
        'Sacred Heart Pioneers', 'South Alabama Jaguars', 'Samford Bulldogs',
        'South Carolina Gamecocks', 'South Carolina State Bulldogs', 'South Dakota State Jackrabbits',
        'San Diego State Aztecs', 'Southeastern Louisiana Lions', 'Southeast Missouri State Red Hawks',
        'Stephen F. Austin Lumberjacks', 'South Florida Bulls', 'St Francis (PA) Red Flash',
        'Sam Houston State Bearkats', 'Southern Illinois Salukis', 'San Jose State Spartans',
        'Southern Mississippi Golden Eagles', 'SMU Mustangs', 'Southern Jaguars',
        'Stanford Cardinal', 'Stony Brook Seawolves', 'Stetson Hatters',
        'Southern Utah Thunderbirds', 'Syracuse Orange', 'Tarleton State',
        'Chattanooga Mocs', 'TCU Horned Frogs', 'Temple Owls',
        'Tennessee Volunteers', 'Tennessee Tech Golden Eagles', 'Texas Longhorns',
        'Tulane Green Wave', 'Tulsa Golden Hurricane', 'UT Martin Skyhawks',
        'Tennessee State Tigers', 'Toledo Rockets', 'Troy Trojans',
        'Towson Tigers', 'Texas A&M Aggies', 'Texas A&M-Commerce Lions',
        'Texas Southern Tigers', 'Texas State Bobcats', 'Texas Tech Red Raiders',
        'UAB Blazers', 'UCLA Bruins', 'North Dakota Fighting Hawks',
        'UNLV Rebels', 'Rhode Island Rams', 'USC Trojans',
        'South Dakota Coyotes', 'Utah Utes', 'Utah Tech Trailblazers',
        'UTEP Miners', 'UTSA Roadrunners', 'Utah State Aggies',
        'Valparaiso Beacons', 'Vanderbilt Commodores', 'Villanova Wildcats',
        'Virginia Cavaliers', 'VMI Keydets', 'Virginia Tech Hokies',
        'Wagner Seahawks', 'Wake Forest Demon Deacons', 'William & Mary Tribe',
        'Washington Huskies', 'Washington State Cougars', 'Western Carolina Catamounts',
        'Weber State Wildcats', 'Western Illinois Leathernecks', 'Wisconsin Badgers',
        'Western Kentucky Hilltoppers', 'Western Michigan Broncos', 'Wofford Terriers',
        'West Virginia Mountaineers', 'Wyoming Cowboys', 'Yale Bulldogs',
        'Youngstown State Penguins',
    ],
    'ncaab': [
        'Alabama Crimson Tide', 'Arizona Wildcats', 'Arizona State Sun Devils',
        'Arkansas Razorbacks', 'Auburn Tigers', 'Baylor Bears', 'BYU Cougars',
        'California Golden Bears', 'Cincinnati Bearcats', 'Clemson Tigers', 'Colorado Buffaloes',
        'Colorado State Rams', 'UConn Huskies', 'Creighton Bluejays', 'Dayton Flyers',
        'Duke Blue Devils', 'Florida Gators', 'Florida State Seminoles', 'Gonzaga Bulldogs',
        'Georgia Bulldogs', 'Houston Cougars', 'Illinois Fighting Illini', 'Indiana Hoosiers',
        'Iowa Hawkeyes', 'Iowa State Cyclones', 'Kansas Jayhawks', 'Kansas State Wildcats',
        'Kentucky Wildcats', 'LSU Tigers', 'Maryland Terrapins', 'Memphis Tigers',
        'Michigan Wolverines', 'Michigan State Spartans', 'Missouri Tigers', 'Nebraska Cornhuskers',
        'North Carolina Tar Heels', 'NC State Wolfpack', 'Notre Dame Fighting Irish',
        'Ohio State Buckeyes', 'Oklahoma Sooners', 'Oklahoma State Cowboys', 'Ole Miss Rebels',
        'Oregon Ducks', 'Oregon State Beavers', 'Penn State Nittany Lions', 'Pittsburgh Panthers',
        'Purdue Boilermakers', 'Rutgers Scarlet Knights', 'San Diego State Aztecs',
        'SMU Mustangs', 'South Carolina Gamecocks', "St. John's Red Storm", 'Stanford Cardinal',
        'Syracuse Orange', 'TCU Horned Frogs', 'Tennessee Volunteers', 'Texas Longhorns',
        'Texas A&M Aggies', 'Texas Tech Red Raiders', 'UCLA Bruins', 'UNLV Rebels',
        'USC Trojans', 'Utah Utes', 'Utah State Aggies', 'Vanderbilt Commodores', 'VCU Rams',
        'Villanova Wildcats', 'Virginia Cavaliers', 'Virginia Tech Hokies',
        'Wake Forest Demon Deacons', 'Washington Huskies', 'West Virginia Mountaineers',
        'Wisconsin Badgers', 'Xavier Musketeers',
    ],
}


def team_slug(name):
    return re.sub(r'[^a-z0-9-]', '', name.lower().replace(' ', '-'))


def resolve_team_slug(sport, slug):
    """Given a sport key (nba/nfl/mlb/nhl/ncaaf/ncaab) and a team slug, return the
    full odds-api-style team name, or None if not found."""
    for name in SPORT_TEAMS.get(sport, []):
        if team_slug(name) == slug:
            return name
    return None
